name: Node.js CI Training Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    rus-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Success message
        run echo "Pipeline run sucessfully!"
